obj-$(CONFIG_FB_EINK_SHIM)  += eink_fb_shim.o
eink_fb_shim-objs           := einkfb_shim.o        \
                               einkfb_shim_mario.o

obj-$(CONFIG_FB_EINK_PNLCD) += eink_fb_pnlcd.o
eink_fb_pnlcd-objs          := einkfb_pnlcd.o       \
                               pn_lcd.o
