/* Generated by makegdkpixbufalias.pl */

#ifndef DISABLE_VISIBILITY

#include <glib.h>

#ifdef G_HAVE_GNUC_VISIBILITY

#define IN_FILE(x) 1
#define IN_HEADER defined

#if IN_HEADER(GDK_PIXBUF_CORE_H)
#if IN_FILE(__GDK_PIXBUF_C__)
extern __typeof (gdk_pixbuf_error_quark) IA__gdk_pixbuf_error_quark __attribute((visibility("hidden")));
#define gdk_pixbuf_error_quark IA__gdk_pixbuf_error_quark

extern __typeof (gdk_pixbuf_get_type) IA__gdk_pixbuf_get_type __attribute((visibility("hidden"))) G_GNUC_CONST;
#define gdk_pixbuf_get_type IA__gdk_pixbuf_get_type

#ifndef GDK_PIXBUF_DISABLE_DEPRECATED
extern __typeof (gdk_pixbuf_ref) IA__gdk_pixbuf_ref __attribute((visibility("hidden")));
#define gdk_pixbuf_ref IA__gdk_pixbuf_ref

extern __typeof (gdk_pixbuf_unref) IA__gdk_pixbuf_unref __attribute((visibility("hidden")));
#define gdk_pixbuf_unref IA__gdk_pixbuf_unref

#endif
extern __typeof (gdk_pixbuf_new) IA__gdk_pixbuf_new __attribute((visibility("hidden")));
#define gdk_pixbuf_new IA__gdk_pixbuf_new

extern __typeof (gdk_pixbuf_get_bits_per_sample) IA__gdk_pixbuf_get_bits_per_sample __attribute((visibility("hidden")));
#define gdk_pixbuf_get_bits_per_sample IA__gdk_pixbuf_get_bits_per_sample

extern __typeof (gdk_pixbuf_get_colorspace) IA__gdk_pixbuf_get_colorspace __attribute((visibility("hidden")));
#define gdk_pixbuf_get_colorspace IA__gdk_pixbuf_get_colorspace

extern __typeof (gdk_pixbuf_get_has_alpha) IA__gdk_pixbuf_get_has_alpha __attribute((visibility("hidden")));
#define gdk_pixbuf_get_has_alpha IA__gdk_pixbuf_get_has_alpha

extern __typeof (gdk_pixbuf_get_height) IA__gdk_pixbuf_get_height __attribute((visibility("hidden")));
#define gdk_pixbuf_get_height IA__gdk_pixbuf_get_height

extern __typeof (gdk_pixbuf_get_n_channels) IA__gdk_pixbuf_get_n_channels __attribute((visibility("hidden")));
#define gdk_pixbuf_get_n_channels IA__gdk_pixbuf_get_n_channels

extern __typeof (gdk_pixbuf_get_pixels) IA__gdk_pixbuf_get_pixels __attribute((visibility("hidden")));
#define gdk_pixbuf_get_pixels IA__gdk_pixbuf_get_pixels

extern __typeof (gdk_pixbuf_get_rowstride) IA__gdk_pixbuf_get_rowstride __attribute((visibility("hidden")));
#define gdk_pixbuf_get_rowstride IA__gdk_pixbuf_get_rowstride

extern __typeof (gdk_pixbuf_get_width) IA__gdk_pixbuf_get_width __attribute((visibility("hidden")));
#define gdk_pixbuf_get_width IA__gdk_pixbuf_get_width

extern __typeof (gdk_pixbuf_get_option) IA__gdk_pixbuf_get_option __attribute((visibility("hidden")));
#define gdk_pixbuf_get_option IA__gdk_pixbuf_get_option

extern __typeof (gdk_pixbuf_copy) IA__gdk_pixbuf_copy __attribute((visibility("hidden")));
#define gdk_pixbuf_copy IA__gdk_pixbuf_copy

extern __typeof (gdk_pixbuf_new_subpixbuf) IA__gdk_pixbuf_new_subpixbuf __attribute((visibility("hidden")));
#define gdk_pixbuf_new_subpixbuf IA__gdk_pixbuf_new_subpixbuf

extern __typeof (gdk_pixbuf_fill) IA__gdk_pixbuf_fill __attribute((visibility("hidden")));
#define gdk_pixbuf_fill IA__gdk_pixbuf_fill

#endif
#endif
#if IN_HEADER(GDK_PIXBUF_CORE_H)
#if IN_FILE(__GDK_PIXBUF_DATA_C__)
extern __typeof (gdk_pixbuf_new_from_data) IA__gdk_pixbuf_new_from_data __attribute((visibility("hidden")));
#define gdk_pixbuf_new_from_data IA__gdk_pixbuf_new_from_data

#endif
#endif
#if IN_HEADER(GDK_PIXBUF_CORE_H)
#if IN_FILE(__GDK_PIXBUF_IO_C__)
extern __typeof (gdk_pixbuf_new_from_file) IA__gdk_pixbuf_new_from_file __attribute((visibility("hidden")));
#define gdk_pixbuf_new_from_file IA__gdk_pixbuf_new_from_file

#ifdef G_OS_WIN32
extern __typeof (gdk_pixbuf_new_from_file_utf8) IA__gdk_pixbuf_new_from_file_utf8 __attribute((visibility("hidden")));
#define gdk_pixbuf_new_from_file_utf8 IA__gdk_pixbuf_new_from_file_utf8

#endif
extern __typeof (gdk_pixbuf_new_from_file_at_size) IA__gdk_pixbuf_new_from_file_at_size __attribute((visibility("hidden")));
#define gdk_pixbuf_new_from_file_at_size IA__gdk_pixbuf_new_from_file_at_size

#ifdef G_OS_WIN32
extern __typeof (gdk_pixbuf_new_from_file_at_size_utf8) IA__gdk_pixbuf_new_from_file_at_size_utf8 __attribute((visibility("hidden")));
#define gdk_pixbuf_new_from_file_at_size_utf8 IA__gdk_pixbuf_new_from_file_at_size_utf8

#endif
extern __typeof (gdk_pixbuf_new_from_file_at_scale) IA__gdk_pixbuf_new_from_file_at_scale __attribute((visibility("hidden")));
#define gdk_pixbuf_new_from_file_at_scale IA__gdk_pixbuf_new_from_file_at_scale

#ifdef G_OS_WIN32
extern __typeof (gdk_pixbuf_new_from_file_at_scale_utf8) IA__gdk_pixbuf_new_from_file_at_scale_utf8 __attribute((visibility("hidden")));
#define gdk_pixbuf_new_from_file_at_scale_utf8 IA__gdk_pixbuf_new_from_file_at_scale_utf8

#endif
extern __typeof (gdk_pixbuf_new_from_xpm_data) IA__gdk_pixbuf_new_from_xpm_data __attribute((visibility("hidden")));
#define gdk_pixbuf_new_from_xpm_data IA__gdk_pixbuf_new_from_xpm_data

extern __typeof (gdk_pixbuf_new_from_stream) IA__gdk_pixbuf_new_from_stream __attribute((visibility("hidden")));
#define gdk_pixbuf_new_from_stream IA__gdk_pixbuf_new_from_stream

extern __typeof (gdk_pixbuf_new_from_stream_at_scale) IA__gdk_pixbuf_new_from_stream_at_scale __attribute((visibility("hidden")));
#define gdk_pixbuf_new_from_stream_at_scale IA__gdk_pixbuf_new_from_stream_at_scale

extern __typeof (gdk_pixbuf_save) IA__gdk_pixbuf_save __attribute((visibility("hidden"))) G_GNUC_NULL_TERMINATED;
#define gdk_pixbuf_save IA__gdk_pixbuf_save

#ifdef G_OS_WIN32
extern __typeof (gdk_pixbuf_save_utf8) IA__gdk_pixbuf_save_utf8 __attribute((visibility("hidden")));
#define gdk_pixbuf_save_utf8 IA__gdk_pixbuf_save_utf8

#endif
extern __typeof (gdk_pixbuf_save_to_buffer) IA__gdk_pixbuf_save_to_buffer __attribute((visibility("hidden"))) G_GNUC_NULL_TERMINATED;
#define gdk_pixbuf_save_to_buffer IA__gdk_pixbuf_save_to_buffer

extern __typeof (gdk_pixbuf_save_to_bufferv) IA__gdk_pixbuf_save_to_bufferv __attribute((visibility("hidden")));
#define gdk_pixbuf_save_to_bufferv IA__gdk_pixbuf_save_to_bufferv

extern __typeof (gdk_pixbuf_save_to_callback) IA__gdk_pixbuf_save_to_callback __attribute((visibility("hidden"))) G_GNUC_NULL_TERMINATED;
#define gdk_pixbuf_save_to_callback IA__gdk_pixbuf_save_to_callback

extern __typeof (gdk_pixbuf_save_to_callbackv) IA__gdk_pixbuf_save_to_callbackv __attribute((visibility("hidden")));
#define gdk_pixbuf_save_to_callbackv IA__gdk_pixbuf_save_to_callbackv

extern __typeof (gdk_pixbuf_savev) IA__gdk_pixbuf_savev __attribute((visibility("hidden")));
#define gdk_pixbuf_savev IA__gdk_pixbuf_savev

#ifdef G_OS_WIN32
extern __typeof (gdk_pixbuf_savev_utf8) IA__gdk_pixbuf_savev_utf8 __attribute((visibility("hidden")));
#define gdk_pixbuf_savev_utf8 IA__gdk_pixbuf_savev_utf8

#endif
extern __typeof (gdk_pixbuf_save_to_stream) IA__gdk_pixbuf_save_to_stream __attribute((visibility("hidden")));
#define gdk_pixbuf_save_to_stream IA__gdk_pixbuf_save_to_stream

#endif
#endif
#if IN_HEADER(GDK_PIXBUF_CORE_H)
#if IN_FILE(__GDK_PIXDATA_C__)
extern __typeof (gdk_pixbuf_new_from_inline) IA__gdk_pixbuf_new_from_inline __attribute((visibility("hidden")));
#define gdk_pixbuf_new_from_inline IA__gdk_pixbuf_new_from_inline

#endif
#endif
#if IN_HEADER(GDK_PIXBUF_CORE_H)
#if IN_FILE(__GDK_PIXBUF_UTIL_C__)
extern __typeof (gdk_pixbuf_add_alpha) IA__gdk_pixbuf_add_alpha __attribute((visibility("hidden")));
#define gdk_pixbuf_add_alpha IA__gdk_pixbuf_add_alpha

extern __typeof (gdk_pixbuf_copy_area) IA__gdk_pixbuf_copy_area __attribute((visibility("hidden")));
#define gdk_pixbuf_copy_area IA__gdk_pixbuf_copy_area

extern __typeof (gdk_pixbuf_saturate_and_pixelate) IA__gdk_pixbuf_saturate_and_pixelate __attribute((visibility("hidden")));
#define gdk_pixbuf_saturate_and_pixelate IA__gdk_pixbuf_saturate_and_pixelate

extern __typeof (gdk_pixbuf_apply_embedded_orientation) IA__gdk_pixbuf_apply_embedded_orientation __attribute((visibility("hidden")));
#define gdk_pixbuf_apply_embedded_orientation IA__gdk_pixbuf_apply_embedded_orientation

#endif
#endif
#if IN_HEADER(GDK_PIXBUF_TRANSFORM_H)
#if IN_FILE(__GDK_PIXBUF_SCALE_C__)
extern __typeof (gdk_pixbuf_rotate_simple) IA__gdk_pixbuf_rotate_simple __attribute((visibility("hidden")));
#define gdk_pixbuf_rotate_simple IA__gdk_pixbuf_rotate_simple

extern __typeof (gdk_pixbuf_scale) IA__gdk_pixbuf_scale __attribute((visibility("hidden")));
#define gdk_pixbuf_scale IA__gdk_pixbuf_scale

extern __typeof (gdk_pixbuf_scale_simple) IA__gdk_pixbuf_scale_simple __attribute((visibility("hidden")));
#define gdk_pixbuf_scale_simple IA__gdk_pixbuf_scale_simple

extern __typeof (gdk_pixbuf_flip) IA__gdk_pixbuf_flip __attribute((visibility("hidden")));
#define gdk_pixbuf_flip IA__gdk_pixbuf_flip

extern __typeof (gdk_pixbuf_composite) IA__gdk_pixbuf_composite __attribute((visibility("hidden")));
#define gdk_pixbuf_composite IA__gdk_pixbuf_composite

extern __typeof (gdk_pixbuf_composite_color) IA__gdk_pixbuf_composite_color __attribute((visibility("hidden")));
#define gdk_pixbuf_composite_color IA__gdk_pixbuf_composite_color

extern __typeof (gdk_pixbuf_composite_color_simple) IA__gdk_pixbuf_composite_color_simple __attribute((visibility("hidden")));
#define gdk_pixbuf_composite_color_simple IA__gdk_pixbuf_composite_color_simple

#endif
#endif
#if IN_HEADER(GDK_PIXBUF_ANIMATION_H)
#if IN_FILE(__GDK_PIXBUF_ANIMATION_C__)
extern __typeof (gdk_pixbuf_animation_get_height) IA__gdk_pixbuf_animation_get_height __attribute((visibility("hidden")));
#define gdk_pixbuf_animation_get_height IA__gdk_pixbuf_animation_get_height

extern __typeof (gdk_pixbuf_animation_get_iter) IA__gdk_pixbuf_animation_get_iter __attribute((visibility("hidden")));
#define gdk_pixbuf_animation_get_iter IA__gdk_pixbuf_animation_get_iter

extern __typeof (gdk_pixbuf_animation_get_static_image) IA__gdk_pixbuf_animation_get_static_image __attribute((visibility("hidden")));
#define gdk_pixbuf_animation_get_static_image IA__gdk_pixbuf_animation_get_static_image

extern __typeof (gdk_pixbuf_animation_get_type) IA__gdk_pixbuf_animation_get_type __attribute((visibility("hidden"))) G_GNUC_CONST;
#define gdk_pixbuf_animation_get_type IA__gdk_pixbuf_animation_get_type

extern __typeof (gdk_pixbuf_animation_get_width) IA__gdk_pixbuf_animation_get_width __attribute((visibility("hidden")));
#define gdk_pixbuf_animation_get_width IA__gdk_pixbuf_animation_get_width

extern __typeof (gdk_pixbuf_animation_is_static_image) IA__gdk_pixbuf_animation_is_static_image __attribute((visibility("hidden")));
#define gdk_pixbuf_animation_is_static_image IA__gdk_pixbuf_animation_is_static_image

extern __typeof (gdk_pixbuf_animation_iter_advance) IA__gdk_pixbuf_animation_iter_advance __attribute((visibility("hidden")));
#define gdk_pixbuf_animation_iter_advance IA__gdk_pixbuf_animation_iter_advance

extern __typeof (gdk_pixbuf_animation_iter_get_delay_time) IA__gdk_pixbuf_animation_iter_get_delay_time __attribute((visibility("hidden")));
#define gdk_pixbuf_animation_iter_get_delay_time IA__gdk_pixbuf_animation_iter_get_delay_time

extern __typeof (gdk_pixbuf_animation_iter_get_pixbuf) IA__gdk_pixbuf_animation_iter_get_pixbuf __attribute((visibility("hidden")));
#define gdk_pixbuf_animation_iter_get_pixbuf IA__gdk_pixbuf_animation_iter_get_pixbuf

extern __typeof (gdk_pixbuf_animation_iter_get_type) IA__gdk_pixbuf_animation_iter_get_type __attribute((visibility("hidden"))) G_GNUC_CONST;
#define gdk_pixbuf_animation_iter_get_type IA__gdk_pixbuf_animation_iter_get_type

extern __typeof (gdk_pixbuf_animation_iter_on_currently_loading_frame) IA__gdk_pixbuf_animation_iter_on_currently_loading_frame __attribute((visibility("hidden")));
#define gdk_pixbuf_animation_iter_on_currently_loading_frame IA__gdk_pixbuf_animation_iter_on_currently_loading_frame

extern __typeof (gdk_pixbuf_animation_new_from_file) IA__gdk_pixbuf_animation_new_from_file __attribute((visibility("hidden")));
#define gdk_pixbuf_animation_new_from_file IA__gdk_pixbuf_animation_new_from_file

#ifdef G_OS_WIN32
extern __typeof (gdk_pixbuf_animation_new_from_file_utf8) IA__gdk_pixbuf_animation_new_from_file_utf8 __attribute((visibility("hidden")));
#define gdk_pixbuf_animation_new_from_file_utf8 IA__gdk_pixbuf_animation_new_from_file_utf8

#endif
#ifndef GDK_PIXBUF_DISABLE_DEPRECATED
extern __typeof (gdk_pixbuf_animation_ref) IA__gdk_pixbuf_animation_ref __attribute((visibility("hidden")));
#define gdk_pixbuf_animation_ref IA__gdk_pixbuf_animation_ref

extern __typeof (gdk_pixbuf_animation_unref) IA__gdk_pixbuf_animation_unref __attribute((visibility("hidden")));
#define gdk_pixbuf_animation_unref IA__gdk_pixbuf_animation_unref

#endif
extern __typeof (gdk_pixbuf_non_anim_new) IA__gdk_pixbuf_non_anim_new __attribute((visibility("hidden")));
#define gdk_pixbuf_non_anim_new IA__gdk_pixbuf_non_anim_new

extern __typeof (gdk_pixbuf_non_anim_get_type) IA__gdk_pixbuf_non_anim_get_type __attribute((visibility("hidden"))) G_GNUC_CONST;
#define gdk_pixbuf_non_anim_get_type IA__gdk_pixbuf_non_anim_get_type

#endif
#endif
#if IN_HEADER(GDK_PIXBUF_SIMPLE_ANIM_H)
#if IN_FILE(__GDK_PIXBUF_SIMPLE_ANIM_C__)
extern __typeof (gdk_pixbuf_simple_anim_get_type) IA__gdk_pixbuf_simple_anim_get_type __attribute((visibility("hidden"))) G_GNUC_CONST;
#define gdk_pixbuf_simple_anim_get_type IA__gdk_pixbuf_simple_anim_get_type

extern __typeof (gdk_pixbuf_simple_anim_iter_get_type) IA__gdk_pixbuf_simple_anim_iter_get_type __attribute((visibility("hidden"))) G_GNUC_CONST;
#define gdk_pixbuf_simple_anim_iter_get_type IA__gdk_pixbuf_simple_anim_iter_get_type

extern __typeof (gdk_pixbuf_simple_anim_new) IA__gdk_pixbuf_simple_anim_new __attribute((visibility("hidden")));
#define gdk_pixbuf_simple_anim_new IA__gdk_pixbuf_simple_anim_new

extern __typeof (gdk_pixbuf_simple_anim_add_frame) IA__gdk_pixbuf_simple_anim_add_frame __attribute((visibility("hidden")));
#define gdk_pixbuf_simple_anim_add_frame IA__gdk_pixbuf_simple_anim_add_frame

#endif
#endif
#if IN_HEADER(GDK_PIXBUF_SCALED_ANIM_H)
#if IN_FILE(__GDK_PIXBUF_SCALED_ANIM_C__)
extern __typeof (gdk_pixbuf_scaled_anim_get_type) IA__gdk_pixbuf_scaled_anim_get_type __attribute((visibility("hidden"))) G_GNUC_CONST;
#define gdk_pixbuf_scaled_anim_get_type IA__gdk_pixbuf_scaled_anim_get_type

extern __typeof (gdk_pixbuf_scaled_anim_iter_get_type) IA__gdk_pixbuf_scaled_anim_iter_get_type __attribute((visibility("hidden"))) G_GNUC_CONST;
#define gdk_pixbuf_scaled_anim_iter_get_type IA__gdk_pixbuf_scaled_anim_iter_get_type

#endif
#endif
#if IN_HEADER(GDK_PIXBUF_IO_H)
#if IN_FILE(__GDK_PIXBUF_IO_C__)
extern __typeof (gdk_pixbuf_get_formats) IA__gdk_pixbuf_get_formats __attribute((visibility("hidden")));
#define gdk_pixbuf_get_formats IA__gdk_pixbuf_get_formats

extern __typeof (gdk_pixbuf_format_get_description) IA__gdk_pixbuf_format_get_description __attribute((visibility("hidden")));
#define gdk_pixbuf_format_get_description IA__gdk_pixbuf_format_get_description

extern __typeof (gdk_pixbuf_format_get_extensions) IA__gdk_pixbuf_format_get_extensions __attribute((visibility("hidden")));
#define gdk_pixbuf_format_get_extensions IA__gdk_pixbuf_format_get_extensions

extern __typeof (gdk_pixbuf_format_get_license) IA__gdk_pixbuf_format_get_license __attribute((visibility("hidden")));
#define gdk_pixbuf_format_get_license IA__gdk_pixbuf_format_get_license

extern __typeof (gdk_pixbuf_format_get_mime_types) IA__gdk_pixbuf_format_get_mime_types __attribute((visibility("hidden")));
#define gdk_pixbuf_format_get_mime_types IA__gdk_pixbuf_format_get_mime_types

extern __typeof (gdk_pixbuf_format_get_name) IA__gdk_pixbuf_format_get_name __attribute((visibility("hidden")));
#define gdk_pixbuf_format_get_name IA__gdk_pixbuf_format_get_name

extern __typeof (gdk_pixbuf_format_is_disabled) IA__gdk_pixbuf_format_is_disabled __attribute((visibility("hidden")));
#define gdk_pixbuf_format_is_disabled IA__gdk_pixbuf_format_is_disabled

extern __typeof (gdk_pixbuf_format_is_scalable) IA__gdk_pixbuf_format_is_scalable __attribute((visibility("hidden")));
#define gdk_pixbuf_format_is_scalable IA__gdk_pixbuf_format_is_scalable

extern __typeof (gdk_pixbuf_format_is_writable) IA__gdk_pixbuf_format_is_writable __attribute((visibility("hidden")));
#define gdk_pixbuf_format_is_writable IA__gdk_pixbuf_format_is_writable

extern __typeof (gdk_pixbuf_format_set_disabled) IA__gdk_pixbuf_format_set_disabled __attribute((visibility("hidden")));
#define gdk_pixbuf_format_set_disabled IA__gdk_pixbuf_format_set_disabled

extern __typeof (gdk_pixbuf_get_file_info) IA__gdk_pixbuf_get_file_info __attribute((visibility("hidden")));
#define gdk_pixbuf_get_file_info IA__gdk_pixbuf_get_file_info

#endif
#endif
#if IN_HEADER(GDK_PIXBUF_IO_H)
#if IN_FILE(__GDK_PIXBUF_C__)
extern __typeof (gdk_pixbuf_set_option) IA__gdk_pixbuf_set_option __attribute((visibility("hidden")));
#define gdk_pixbuf_set_option IA__gdk_pixbuf_set_option

#endif
#endif
#if IN_HEADER(GDK_PIXBUF_LOADER_H)
#if IN_FILE(__GDK_PIXBUF_LOADER_C__)
extern __typeof (gdk_pixbuf_loader_close) IA__gdk_pixbuf_loader_close __attribute((visibility("hidden")));
#define gdk_pixbuf_loader_close IA__gdk_pixbuf_loader_close

extern __typeof (gdk_pixbuf_loader_get_animation) IA__gdk_pixbuf_loader_get_animation __attribute((visibility("hidden")));
#define gdk_pixbuf_loader_get_animation IA__gdk_pixbuf_loader_get_animation

extern __typeof (gdk_pixbuf_loader_get_format) IA__gdk_pixbuf_loader_get_format __attribute((visibility("hidden")));
#define gdk_pixbuf_loader_get_format IA__gdk_pixbuf_loader_get_format

extern __typeof (gdk_pixbuf_loader_get_pixbuf) IA__gdk_pixbuf_loader_get_pixbuf __attribute((visibility("hidden")));
#define gdk_pixbuf_loader_get_pixbuf IA__gdk_pixbuf_loader_get_pixbuf

extern __typeof (gdk_pixbuf_loader_get_type) IA__gdk_pixbuf_loader_get_type __attribute((visibility("hidden"))) G_GNUC_CONST;
#define gdk_pixbuf_loader_get_type IA__gdk_pixbuf_loader_get_type

extern __typeof (gdk_pixbuf_loader_new) IA__gdk_pixbuf_loader_new __attribute((visibility("hidden")));
#define gdk_pixbuf_loader_new IA__gdk_pixbuf_loader_new

extern __typeof (gdk_pixbuf_loader_new_with_mime_type) IA__gdk_pixbuf_loader_new_with_mime_type __attribute((visibility("hidden")));
#define gdk_pixbuf_loader_new_with_mime_type IA__gdk_pixbuf_loader_new_with_mime_type

extern __typeof (gdk_pixbuf_loader_new_with_type) IA__gdk_pixbuf_loader_new_with_type __attribute((visibility("hidden")));
#define gdk_pixbuf_loader_new_with_type IA__gdk_pixbuf_loader_new_with_type

extern __typeof (gdk_pixbuf_loader_set_size) IA__gdk_pixbuf_loader_set_size __attribute((visibility("hidden")));
#define gdk_pixbuf_loader_set_size IA__gdk_pixbuf_loader_set_size

extern __typeof (gdk_pixbuf_loader_write) IA__gdk_pixbuf_loader_write __attribute((visibility("hidden")));
#define gdk_pixbuf_loader_write IA__gdk_pixbuf_loader_write

#endif
#endif
#if IN_HEADER(__GDK_PIXBUF_ENUM_TYPES_H__)
#if IN_FILE(__GDK_PIXBUF_ENUM_TYPES_C__)
extern __typeof (gdk_colorspace_get_type) IA__gdk_colorspace_get_type __attribute((visibility("hidden"))) G_GNUC_CONST;
#define gdk_colorspace_get_type IA__gdk_colorspace_get_type

extern __typeof (gdk_interp_type_get_type) IA__gdk_interp_type_get_type __attribute((visibility("hidden"))) G_GNUC_CONST;
#define gdk_interp_type_get_type IA__gdk_interp_type_get_type

extern __typeof (gdk_pixbuf_alpha_mode_get_type) IA__gdk_pixbuf_alpha_mode_get_type __attribute((visibility("hidden"))) G_GNUC_CONST;
#define gdk_pixbuf_alpha_mode_get_type IA__gdk_pixbuf_alpha_mode_get_type

extern __typeof (gdk_pixbuf_rotation_get_type) IA__gdk_pixbuf_rotation_get_type __attribute((visibility("hidden"))) G_GNUC_CONST;
#define gdk_pixbuf_rotation_get_type IA__gdk_pixbuf_rotation_get_type

extern __typeof (gdk_pixbuf_error_get_type) IA__gdk_pixbuf_error_get_type __attribute((visibility("hidden")));
#define gdk_pixbuf_error_get_type IA__gdk_pixbuf_error_get_type

#endif
#endif
#if IN_HEADER(__GDK_PIXDATA_H__)
#if IN_FILE(__GDK_PIXDATA_C__)
extern __typeof (gdk_pixbuf_from_pixdata) IA__gdk_pixbuf_from_pixdata __attribute((visibility("hidden")));
#define gdk_pixbuf_from_pixdata IA__gdk_pixbuf_from_pixdata

extern __typeof (gdk_pixdata_deserialize) IA__gdk_pixdata_deserialize __attribute((visibility("hidden")));
#define gdk_pixdata_deserialize IA__gdk_pixdata_deserialize

extern __typeof (gdk_pixdata_from_pixbuf) IA__gdk_pixdata_from_pixbuf __attribute((visibility("hidden")));
#define gdk_pixdata_from_pixbuf IA__gdk_pixdata_from_pixbuf

extern __typeof (gdk_pixdata_serialize) IA__gdk_pixdata_serialize __attribute((visibility("hidden")));
#define gdk_pixdata_serialize IA__gdk_pixdata_serialize

extern __typeof (gdk_pixdata_to_csource) IA__gdk_pixdata_to_csource __attribute((visibility("hidden")));
#define gdk_pixdata_to_csource IA__gdk_pixdata_to_csource

#endif
#endif

#endif /* G_HAVE_GNUC_VISIBILITY */
#endif /* DISABLE_VISIBILITY */
