#################################################
# Makefile for G2D on S3C6410
# 2008 (C) Samsung Electronics
# Author : joghun.han <jonghun.han@samsung.com>
#################################################


s3c_g2d-y    += s3c_g2d_driver.o

obj-$(CONFIG_VIDEO_G2D)	:= s3c_g2d.o
